networks:
  nightingale:
    driver: bridge

services:
  mysql:
    image: "mysql:8"
    container_name: mysql
    hostname: mysql
    restart: always
    networks:
      - nightingale
    #ports:
    #  - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./volumes/mysql/my.cnf:/etc/my.cnf
      - ./volumes/mysql/data:/volumes
      - ./volumes/mysql/initsql:/docker-entrypoint-initdb.d/

  redis:
    image: "redis:7.0-alpine"
    container_name: n9e-redis
    hostname: redis
    restart: always
    networks:
      - nightingale
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: n9e-victoriametrics
    hostname: victoriametrics
    restart: always
    networks:
      - nightingale
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/victoriametrics:/volumes
    command:
      - "-httpListenAddr=:8428"
      - "-loggerTimezone=Asia/Shanghai"
      - "-storageDataPath=/volumes"
      - "-retentionPeriod=3y"

  nightingale:
    image: flashcatcloud/nightingale:latest
    container_name: n9e-nightingale
    hostname: nightingale
    restart: always
    networks:
      - nightingale
    ports:
      - "17000:17000"
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, redis:6379
    volumes:
      - ./volumes/n9e:/app/etc
    depends_on:
      - mysql
      - redis
      - victoriametrics
    links:
      - mysql:mysql
      - redis:redis
      - victoriametrics:victoriametrics
    command: >
      sh -c "/app/n9e"
