networks:
  n9e-edge:
    driver: bridge

services:
  n9e-edge:
    image: taozig/n9e-edge:latest
    container_name: taozig-n9e-edge
    restart: unless-stopped
    networks:
      - n9e-edge
    ports:
      - "19000:19000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/n9e-edge:/program/etc

  redis:
    image: "redis:7.0-alpine"
    container_name: n9e-edge-redis
    hostname: redis
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - n9e-edge

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: n9e-edge-victoriametrics
    hostname: victoriametrics
    restart: unless-stopped
    networks:
      - n9e-edge
    # 非加密端口，对内访问
    ports:
      - "8428:8428"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/victoriametrics:/volumes
    command:
      - "-httpListenAddr=:8428"
      - "-loggerTimezone=Asia/Shanghai"
      - "-storageDataPath=/volumes"
      - "-retentionPeriod=3y"

  vmauth:
    image: victoriametrics/vmauth:latest
    container_name: n9e-edge-vmauth
    hostname: vmauth
    restart: unless-stopped
    networks:
      - n9e-edge
    # 加密传输端口，对外访问
    ports:
      - "8427:8427"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/vmauth:/volumes
    command:
      - "--loggerTimezone=Asia/Shanghai"
      - "-loggerLevel=INFO"
      - "-auth.config=/volumes/config.yml"