name: "构建 Docker 镜像"

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "构建 Docker 镜像..."

            -
                name: "获取 Build 文件"
                uses: actions/checkout@v4
            -
                name: "获取当前工作目录"
                run: ls -la
            -
                name: "获取N9E文件"
                run: |
                    sudo ./n9e-edge/dockerfile/install.sh
            -
                name: "登录 Docker Hub"
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            -
                name: "构建和推送 Docker 镜像"
                run: |
                    pwd
                    ./n9e-edge/dockerfile/build.sh
            -
                name: "上传 Docker 镜像至 GitHub"
                uses: actions/upload-artifact@v4
                with:
                    name: n9e-edge.tar
                    path: ./n9e-edge/dockerfile/n9e-edge.tar